name: Build Ardour (Linux)

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ardour Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            git \
            libgtkmm-3.0-dev \
            libjack-jackd2-dev \
            libasound2-dev \
            libpulse-dev \
            libcurl4-gnutls-dev \
            liblo-dev \
            liblilv-dev \
            libserd-dev \
            libsord-dev \
            libsratom-dev \
            libboost-all-dev \
            libarchive-dev \
            libaubio-dev \
            libfftw3-dev \
            libfreetype6-dev \
            libglibmm-2.4-dev \
            libsamplerate0-dev \
            libsndfile1-dev \
            libsoundtouch-dev \
            libtag1-dev \
            libxml2-dev \
            python3 \
            python3-pip \
            python3-lxml

      - name: Build Ardour
        run: |
          ./waf configure --prefix=/output
          ./waf build -j$(nproc)
          ./waf install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ardour-linux
          path: /output
