name: Build Ardour (macOS)

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install cmake gtkmm jack boost alsa-lib

      - name: Set up environment variables
        run: |
          export BOOST_ROOT=$(brew --prefix boost)
          export PKG_CONFIG_PATH="$BOOST_ROOT/lib/pkgconfig:$PKG_CONFIG_PATH"

      - name: Build Ardour
        run: |
          ./waf configure --prefix=/output
          ./waf build -j$(sysctl -n hw.ncpu)
          ./waf install

      - name: Package into macOS Application Bundle
        run: |
          cd tools/osx_packaging
          ./osx_build --public

      - name: Upload macOS App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: ardour-macos-app
          path: tools/osx_packaging/*.app
