name: Build Ardour (macOS)

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install boost
          export CPLUS_INCLUDE_PATH=/opt/homebrew/Cellar/boost/1.84.0_1/include
          brew install pkg-config
          brew install glib
          brew install glibmm@2.66
          brew install libsndfile
          brew install libarchive
          export PKG_CONFIG_PATH="/opt/homebrew/opt/libarchive/lib/pkgconfig:$PKG_CONFIG_PATH"
          brew install liblo
          brew install taglib
          brew install vamp-plugin-sdk
          brew install rubberband
          brew install libusb
          brew install jack
          brew install fftw
          brew install aubio
          brew install libpng
          brew install pango
          brew install libsigc++@2
          brew install cairomm@1.14
          brew install pangomm@2.46
          brew install lv2
          brew install cppunit
          brew install libwebsockets
          brew install lrdf
          brew install serd
          brew install sord
          brew install sratom
          brew install lilv

      - name: Set up environment variables
        run: |
          export BOOST_ROOT=$(brew --prefix boost)
          export PKG_CONFIG_PATH="$BOOST_ROOT/lib/pkgconfig:$PKG_CONFIG_PATH"

      - name: Build Ardour
        run: |
          ./waf configure --prefix=/output
          ./waf build -j$(sysctl -n hw.ncpu)
          ./waf install

      - name: Package into macOS Application Bundle
        run: |
          cd tools/osx_packaging
          ./osx_build --public

      - name: Upload macOS App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: ardour-macos-app
          path: tools/osx_packaging/*.app
