name: Build Ardour (Windows)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install msys2
          refreshenv
          pacman -S --needed base-devel mingw-w64-x86_64-gcc cmake

      - name: Build Ardour
        shell: msys2 {0}
        run: |
          ./waf configure --prefix=/output
          ./waf build -j$(nproc)
          ./waf install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ardour-windows
          path: /output
